name: "get and cache dependencies"
description: "get dependencies and cache them"
inputs:
  caching:
    description: "This determines whether to use caching or not"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "whether cache was used or not"
    value: Was cache used? --> ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-depends-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
      shell: bash
